"""Outbound persistence ports. Postgres adapters live in infrastructure/persistence."""

from typing import Protocol
from uuid import UUID

from app.domain.entities.audit_record import AuditRecord
from app.domain.entities.context_pack import ContextPack
from app.domain.entities.document import Document
from app.domain.entities.github_connection import GitHubConnection
from app.domain.entities.issue import Issue
from app.domain.entities.metrics_snapshot import MetricsSnapshot
from app.domain.entities.milestone import Milestone
from app.domain.entities.openspec_change import OpenSpecChange
from app.domain.entities.pull_request import PullRequest
from app.domain.entities.repository import Repository
from app.domain.entities.source_chunk import SourceChunk
from app.domain.entities.source_file import SourceFile
from app.domain.entities.sync_job import SyncJob
from app.domain.entities.sync_run import SyncRun
from app.domain.entities.webhook_delivery import WebhookDelivery


class ConnectionPort(Protocol):
    async def save(self, connection: GitHubConnection) -> None: ...

    async def get(self, connection_id: UUID) -> GitHubConnection | None: ...

    async def get_by_owner(self, owner: str) -> GitHubConnection | None: ...

    async def list_all(self) -> list[GitHubConnection]: ...

    async def delete(self, connection_id: UUID) -> None: ...


class RepositoryPort(Protocol):
    async def save(self, repository: Repository) -> None: ...

    async def save_many(self, repositories: list[Repository]) -> None: ...

    async def get(self, repository_id: UUID) -> Repository | None: ...

    async def get_by_full_name(self, full_name: str) -> Repository | None: ...

    async def list_all(self, *, enabled_only: bool = False) -> list[Repository]: ...


class DocumentPort(Protocol):
    async def save(self, document: Document) -> None: ...

    async def get(self, document_id: UUID) -> Document | None: ...

    async def get_by_path(self, repository_id: UUID, path: str) -> Document | None: ...

    async def list_by_repository(self, repository_id: UUID) -> list[Document]: ...

    async def delete_missing(self, repository_id: UUID, seen_paths: set[str]) -> int: ...


class OpenSpecPort(Protocol):
    async def save(self, change: OpenSpecChange) -> None: ...

    async def list_by_repository(self, repository_id: UUID) -> list[OpenSpecChange]: ...


class IssuePort(Protocol):
    async def save_many(self, issues: list[Issue]) -> None: ...

    async def get_by_number(self, repository_id: UUID, number: int) -> Issue | None: ...

    async def list_by_repository(
        self, repository_id: UUID, *, state: str | None = None, label: str | None = None
    ) -> list[Issue]: ...


class PullRequestPort(Protocol):
    async def save_many(self, pull_requests: list[PullRequest]) -> None: ...

    async def get_by_number(self, repository_id: UUID, number: int) -> PullRequest | None: ...

    async def list_by_repository(
        self, repository_id: UUID, *, state: str | None = None, author: str | None = None
    ) -> list[PullRequest]: ...


class FilePort(Protocol):
    async def replace_tree(self, repository_id: UUID, files: list[SourceFile]) -> None: ...

    async def list_by_repository(self, repository_id: UUID) -> list[SourceFile]: ...

    async def get(self, file_id: UUID) -> SourceFile | None: ...

    async def get_by_path(self, repository_id: UUID, path: str) -> SourceFile | None: ...

    async def save_content(self, file: SourceFile) -> None: ...


class SourceChunkPort(Protocol):
    async def replace_for_file(self, file_id: UUID, chunks: list[SourceChunk]) -> None: ...

    async def delete_for_file(self, file_id: UUID) -> None: ...

    async def list_by_repository(self, repository_id: UUID) -> list[SourceChunk]: ...

    async def get_by_symbol(self, repository_id: UUID, symbol_name: str) -> list[SourceChunk]: ...


class SyncJobPort(Protocol):
    async def save(self, job: SyncJob) -> None: ...

    async def get(self, job_id: UUID) -> SyncJob | None: ...

    async def get_latest(self, repository_id: UUID) -> SyncJob | None: ...

    async def list_recent(self, limit: int = 50) -> list[SyncJob]: ...


class SyncRunPort(Protocol):
    async def record(self, run: SyncRun) -> None: ...

    async def list_recent(self, limit: int = 50) -> list[SyncRun]: ...


class ContextPackPort(Protocol):
    async def save(self, pack: ContextPack) -> None: ...

    async def find_cached(
        self, repository_id: UUID, query: str, mode: str, sync_timestamp: str
    ) -> ContextPack | None: ...


class AuditPort(Protocol):
    async def record(self, entry: AuditRecord) -> None: ...

    async def list_recent(self, limit: int = 100) -> list[AuditRecord]: ...


class WebhookDeliveryPort(Protocol):
    async def exists(self, delivery_id: str) -> bool: ...

    async def record(self, delivery: WebhookDelivery) -> None: ...

    async def list_recent(self, limit: int = 100) -> list[WebhookDelivery]: ...


class MetricsHistoryPort(Protocol):
    async def record(self, snapshot: MetricsSnapshot) -> None: ...

    async def list_window(
        self, repository_id: UUID, *, days: int = 180
    ) -> list[MetricsSnapshot]: ...

    async def list_all_windows(
        self, *, days: int = 180
    ) -> dict[UUID, list[MetricsSnapshot]]: ...

    async def prune(self, *, daily_days: int = 180) -> int: ...


class MilestonePort(Protocol):
    async def replace_for_repository(
        self, repository_id: UUID, milestones: list[Milestone]
    ) -> None: ...

    async def list_by_repository(self, repository_id: UUID) -> list[Milestone]: ...

    async def list_all(self) -> dict[UUID, list[Milestone]]: ...
